// Mapping des catégories avec des icônes Ionicons valides
export const DEFAULT_INCOME_CATEGORIES = [
  {
    name: "Salaire",
    type: "income" as const,
    color: "#22c55e",
    icon: "cash-outline", // Ionicons valide
    isDefault: true,
  },
  {
    name: "Freelance",
    type: "income" as const,
    color: "#16a34a",
    icon: "briefcase-outline",
    isDefault: true,
  },
  {
    name: "Investissements",
    type: "income" as const,
    color: "#8b5cf6",
    icon: "trending-up-outline",
    isDefault: true,
  },
  {
    name: "Rentes",
    type: "income" as const,
    color: "#06b6d4",
    icon: "home-outline",
    isDefault: true,
  },
  {
    name: "Allocations",
    type: "income" as const,
    color: "#f59e0b",
    icon: "people-outline",
    isDefault: true,
  },
  {
    name: "Ventes",
    type: "income" as const,
    color: "#ec4899",
    icon: "cart-outline",
    isDefault: true,
  },
  {
    name: "Primes",
    type: "income" as const,
    color: "#14b8a6",
    icon: "gift-outline",
    isDefault: true,
  },
  {
    name: "Autres revenus",
    type: "income" as const,
    color: "#64748b",
    icon: "wallet-outline",
    isDefault: true,
  },
];

export const DEFAULT_EXPENSE_CATEGORIES = [
  {
    name: "Nourriture",
    type: "expense" as const,
    color: "#ef4444",
    icon: "restaurant-outline",
    isDefault: true,
  },
  {
    name: "Transport",
    type: "expense" as const,
    color: "#f59e0b",
    icon: "bus-outline",
    isDefault: true,
  },
  {
    name: "Loyer",
    type: "expense" as const,
    color: "#3b82f6",
    icon: "home-outline",
    isDefault: true,
  },
  {
    name: "Santé",
    type: "expense" as const,
    color: "#ec4899",
    icon: "medical-outline",
    isDefault: true,
  },
  {
    name: "Divertissement",
    type: "expense" as const,
    color: "#06b6d4",
    icon: "game-controller-outline",
    isDefault: true,
  },
  {
    name: "Factures",
    type: "expense" as const,
    color: "#8b5cf6",
    icon: "document-text-outline",
    isDefault: true,
  },
  {
    name: "Shopping",
    type: "expense" as const,
    color: "#f43f5e",
    icon: "bag-outline",
    isDefault: true,
  },
  {
    name: "Éducation",
    type: "expense" as const,
    color: "#10b981",
    icon: "school-outline",
    isDefault: true,
  },
  {
    name: "Voyage",
    type: "expense" as const,
    color: "#0ea5e9",
    icon: "airplane-outline",
    isDefault: true,
  },
  {
    name: "Assurances",
    type: "expense" as const,
    color: "#6366f1",
    icon: "shield-outline",
    isDefault: true,
  },
  {
    name: "Abonnements",
    type: "expense" as const,
    color: "#a855f7",
    icon: "phone-portrait-outline",
    isDefault: true,
  },
  {
    name: "Animaux",
    type: "expense" as const,
    color: "#84cc16",
    icon: "paw-outline",
    isDefault: true,
  },
  {
    name: "Cadeaux",
    type: "expense" as const,
    color: "#f97316",
    icon: "gift-outline",
    isDefault: true,
  },
  {
    name: "Beauté",
    type: "expense" as const,
    color: "#f0abfc",
    icon: "color-palette-outline",
    isDefault: true,
  },
  {
    name: "Sport",
    type: "expense" as const,
    color: "#22d3ee",
    icon: "basketball-outline",
    isDefault: true,
  },
  {
    name: "Rénovations",
    type: "expense" as const,
    color: "#78716c",
    icon: "construct-outline",
    isDefault: true,
  },
  {
    name: "Impôts",
    type: "expense" as const,
    color: "#dc2626",
    icon: "stats-chart-outline",
    isDefault: true,
  },
  {
    name: "Autres dépenses",
    type: "expense" as const,
    color: "#64748b",
    icon: "create-outline",
    isDefault: true,
  },
];